### ISSUE TITLE
CI/Hosted Pipelines `content-hash : compute-md5sum` Step Discrepencies

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/operator-pipelines#377] opened 2022-11-22 20:09 UTC
There seems to be discrepancies with how this step works between the CI and Hosted pipeline. More specifically when `–digest-pinning` is enabled on the CI pipeline, and pinning has already occurred, the md5sum calculated on the CSV.yaml is not the same value that the Hosted pipeline calculates. This forces the Hosted pipeline to run preflight for operators which cannot be tested in the Hosted pipeline.

 
Another note, no matter which pipeline runs (or what flags the CI pipeline is run with) preflight's calculations of the hash for the CSV.yaml that it gets from the bundle, is always the same value.

Jira: CLOUDWF-8454

**Comment by acornett21** [comment] 2022-11-22 20:11
@tamurray Here is the issue for the problem you experienced. I also created an internal Jira.

**Comment by zcahana** [comment] 2022-12-25 21:51
We (redis-enterprise-operator) have also hit this issue.

Looking further into it, I think the `digest-pinning` step is creating additional `.relatedImages` entries in the CSV (e.g., [this commit](https://github.com/redhat-openshift-ecosystem/certified-operators/commit/29b8adfb73d626f27561fa5ea99ccb2e61a9ff92) auto-generated by the `commit-pinned-digest` step). 

If no tag-->digest replacements are detected, then the modified CSV isn't commit/pushed upstream, but the modified local file results with a different md5 checksum --> preflight gets triggered on the hosted pipeline.

I'm not sure what's the purpose of these auto-generated `.relatedImages` entries, but assuming they should be there, maybe the digest-pinning/commit-pinned-digest steps should be updated to detect such changes and commit/push them?

**Comment by Allda** [comment] 2023-05-24 08:43
Hey guys, sorry for the late response I am looking at the issue now. All references to remote images need to be pinned by the digests. That is why we have the `digest-pinning` task that translates tags into digest in CSV. In case you enable this feature by using `–digest-pinning` flag and the pipeline detects a dirty repository after the pinning step it automatically creates a new commit/branch in your repository `commit-pinned-digest` and the hashing step uses updated CSV. Then you have to open a PR with the new branch in order to match the hash from CI and hosted pipeline.

Do you have a full output of the CI pipeline so I can analyze where the problem is? Is there a chance that you didn't open the PR with the commit generated by `commit-pinned-digest`? Thank you

**Comment by acornett21** [comment] 2023-05-24 13:49
> Then you have to open a PR with the new branch in order to match the hash from CI and hosted pipeline.

@Allda Is this documented somewhere that the PR needs to be opened with the new `commit-pinned-digest` branch? This is the first that I'm even hearing of this.

**Comment by Allda** [comment] 2023-05-24 14:04
@acornett21 I am not sure if it is documented :/ If you enable the `submit` parameter the CI pipeline automatically opens a PR with the new pinned branch. If you don't use this option it is up to you to open PR with a correct commit. I'll check with doc team and potentially add this step to the doc.

Based on this feature do you think the PR could be opened manually with the old commit which caused the mismatch between pipeline hashes?

**Comment by mantomas** [comment] 2023-05-25 09:40
@zcahana thanks for your last comment, it put us on the track where the issue might be. I was able to rerun the pining step on your branch locally and the `.relatedImages` section was indeed changed and the md5sum on this file corresponds with logs from CI pipeline. The problem is that we are testing only `replacements.json` (which is empty {} after the pinning) but the changes are reported in `references.json` and we should add it to the check if commit is needed.

**Comment by mantomas** [comment] 2023-05-29 15:15
We have decided to [reset git working branch](https://github.com/redhat-openshift-ecosystem/operator-pipelines/pull/449) to the state before `pin-digest` if no actual pinning occurred. This will prevent the md5sum from ci pipeline to be calculated against the files in a different state. 
Also, the `relatedImages` section is always recreated by the pinning tool, so there will be most certainly always some differences/git changes in CSV if it was originally pinned by different tool than the one used by the pipeline.

**Comment by Allda** [comment] 2023-06-28 09:59
The issue has been resolved in https://github.com/redhat-openshift-ecosystem/operator-pipelines/pull/449

**Closed by Allda** 2023-06-28 09:59 UTC
